# Generated by Django 4.1.2 on 2022-10-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_category_project_client_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, default=None, upload_to='project_pics'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, default=None, upload_to='project_pics'),
        ),
    ]
