# Generated by Django 4.1.2 on 2022-10-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image1',
            new_name='image',
        ),
    ]
