# Generated by Django 4.1.2 on 2022-10-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_image1_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='comp',
            field=models.TextField(default='hello', max_length=5000),
            preserve_default=False,
        ),
    ]
